version: '3.7'
services:
  slack-backend:
    container_name: slack-backend
    image: raulchall/system-events-slack-backend:latest
    build:
      context: slack-app-backend
      dockerfile: src/Dockerfile
    env_file:
      - slack-app-backend/src/envvars
    networks:
      - system-events
    ports:
      - "80"

  system-events:
    container_name: system-events
    image: raulchall/system-events:latest
    build:
      context: system-events
      dockerfile: src/Dockerfile
    env_file:
      - system-events/src/envvars
    volumes:
      - ./system-events/src/config.yml:/config/config.yml
    networks:
      - system-events
    ports:
      - "80"
  
  grafana:
    image: grafana/grafana:6.6.0
    container_name: system-events-grafana
    ports:
      - "3000"
    networks:
      - system-events
    volumes:
      - grafana-storage:/var/lib/grafana

  elasticsearch:
    image: elasticsearch:5.6.3
    container_name: system-events-elasticsearch
    ports:
      - "9200"
      - "9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - discovery.type=single-node
    networks:
      - system-events

  es-index-creator:
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    networks:
      - system-events

  kibana:
    image: 'kibana:5.6.15'
    container_name: system-events-kibana
    ports:
      - '5601'
    networks:
      - system-events
    depends_on:
      - elasticsearch
  
  prometheus:
    image: prom/prometheus:v2.15.2
    container_name: system-events-prometheus
    ports: 
      - "9090"
      - "9091"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - system-events
  
  localstack:
    image: localstack/localstack
    container_name: system-events-localstack
    ports:
      - "4575"
    networks:
      - system-events
  
  subscription-sns-topic-deployer:
    build:
      context: subscriptions
      dockerfile: Dockerfile
    env_file:
      - subscriptions/envvars
    networks:
      - system-events

networks:
  system-events:
    external:
      name: system-events

volumes:
  grafana-storage:
  esdata:
